### ISSUE TITLE
Upgrade easier on fingers

### ISSUE THREAD

**Issue by spanezz** [HassanHeydariNasab/defendo#13]
Hello,

currently, to upgrade a turret I need to drag it inside the base, create a new turrent and drag the new turret inside the base. Repeating this hundreds of times causes quite a bit of strain in my finger and wrist, and makes the game too painful for me to enjoy.

My proposal for making the interface a bit swifter to use is that if there is a turret inside the base and I tap the button to buy a new one, then no new turrent is created and the turrent inside the base is upgraded instead.

That way I could bring a turret inside the base, tap update 20 times or however many I need, and move it back to its pad, all rather easily

**Comment by HassanHeydariNasab** [comment]
another suggestion #11
