### ISSUE TITLE
Crash ar level 26

### ISSUE THREAD

**Issue by MartinBlanchard** [HassanHeydariNasab/defendo#21]
Crash at level 26 without saving progress

**Comment by HassanHeydariNasab** [comment]
- in new era or old era?
- what happend?
- which version?
- is it a persistent problem? (everytime in level 26?)

**Comment by MartinBlanchard** [comment]
- in new era or old era?  NEW
- what happend?          I was playing and then everything stop : the app closed. At reboot no score saved.
- which version?          The version available on f-droid at this time (see email date) I think 2.3.1
- is it a persistent problem? (everytime in level 26?)  Level 26 or 27 I'm not sure because it was very suddenly   persistent ? : I don't now because I never try again it is like losing time :-(

**Comment by davidak** [comment]
I'm currently at level 31, no crash.
So it might not be a general bug in the game. Or it is now fixed.
What device have you used, @MartinBlanchard?
I suggest closing this issue until someone has it again with the current version.
