### ISSUE TITLE
don't show technical details to users

### ISSUE THREAD

**Issue by davidak** [HassanHeydariNasab/defendo#49]
they are fine in the README on github, for (potential) developers, but confuse gamers und normal users.

so remove them from the game and F-Droid description.

**Comment by HassanHeydariNasab** [comment]
I prefer to show "This made using Godot" to the users. maybe a developer find it.

**Comment by davidak** [comment]
Ok, i respect that. Its better than "The game is developing using Godot v2.1.4." I think the version is not relevant to anyone.
