### ISSUE TITLE
Explain how to translate

### ISSUE THREAD

**Issue by RyDroid** [HassanHeydariNasab/defendo#5]
Hi.

It would be useful to know how the game could be translated.

Regards.

**Comment by HassanHeydariNasab** [comment]
Hello.
see https://github.com/HassanHeydariNasab/defendo/blob/master/Cxenoj.csv

add your desired language at the first line and translate the strings like english translation at the other lines.

**Comment by RyDroid** [comment]
Ok, thanks. With this name (esperanto I guess) and this file format (for example a po file would have been so easier to find and manipulate), I would never have guessed by myself.

**Comment by RyDroid** [comment]
> If already you helped us, I don't remember; Because now is a time before that!

The last sentence makes no sense with the rest for me. Did you mean "for that" instead of "before that"?

> Nova,New

In French, I have to now if it is neutral, masculine or feminine. I understand english but not esperanto.

> Shooting by laser and ondilo

What "ondilo" is supposed to mean?
https://www.linguee.fr/anglais-francais/search?query=ondilo
https://en.wiktionary.org/w/index.php?search=ondilo

> costs 5 dollars

Why promoting a specific currency? Why not just "costs 5"?

> New era

It seems me strange.
https://www.linguee.fr/francais-anglais/search?source=auto&query=era
Which definition is correct?

**Comment by HassanHeydariNasab** [comment]
> In French, I have to now if it is neutral, masculine or feminine. I understand english but not esperanto.

I think it's neutral. It indicates an enemy.

> What "ondilo" is supposed to mean?

"Ondo" means "Wave" and "Ondilo" is a tool/weapon that produces wave.

> Why promoting a specific currency?

Why not? :smile:

>     New era
> 
> It seems me strange.
> https://www.linguee.fr/francais-anglais/search?source=auto&query=era
> Which definition is correct?

idk, both are the same :thinking:

**Comment by RyDroid** [comment]
> "Ondo" means "Wave" and "Ondilo" is a tool/weapon that produces wave.

I suppose that is not supposed to be translated, is it? In French, "wave" is translated by "vague", so it could easily be translated in "vaguilo".

> > Why promoting a specific currency?
> 
> Why not? 😄

Because many people do not like advertisement and it contributes to enforce the (too) big importance of the USA.

**Comment by HassanHeydariNasab** [comment]
> I suppose that is not supposed to be translated, is it? In French, "wave" is translated by "vague", so it could easily be translated in "vaguilo".
I prefer "Ondilo" itself.

> Because many people do not like advertisement and it contributes to enforce the (too) big importance of the USA.
OK. I'm thinking about a neutral currency like Bitcoin.

**Comment by martinKgG** [comment]
Hi,

I consider to make a german translation of file https://github.com/HassanHeydariNasab/defendo/blob/master/Cxenoj.csv.

But I don't now to change the change file.

And how can I see the result in the game?

Greetings from Berlin, Germany

**Comment by RyDroid** [comment]
@HassanHeydariNasab

> > Because many people do not like advertisement and it contributes to enforce the (too) big importance of the USA.
> 
> OK. I'm thinking about a neutral currency like Bitcoin.

Even if Bitcoin is less commonly viewed as political, it is. Deleting the possibility to states and banks to create money, deleting the dependency of a centralized organization for exchanging money digitally, etc : that is politic. I think that something like DefendCoin would eliminate the political problem.

---

@martinKgG

> I consider to make a german translation. But I don't now to change the change file.

It is a CSV file. The first line is the header, it contains the name of each column. "en" is for English, "fr" for French, etc. To add a new column, just add a comma and then the content of the column.

Let's take a simple example:

```
en,fr
My name is Nicola,Je m’appelle Nicola
I like men,J'aime les hommes
```

If a translation in Spanish is added, the result can be:

```
en,fr,es
My name is Nicola,Je m’appelle Nicola,Me llamo Nicola
I like men,J'aime les hommes,Me gusto los hombres
```

> how can I see the result in the game?

You can compile the game. You can follow the example of the builds of F-Droid. https://gitlab.com/fdroid/fdroiddata/raw/master/metadata/ir.hsn6.defendo.txt

In the APK of F-Droid, the translations are in `assets/Tradukoj/` (unzip the APK to see that). There is one file per language and the extension format is "xl". Unfortunately, it seems to be mostly a binary format. If you know how to produce one, you can just add one in German or replace a current language if it does not detect automatically a new file added, this hack has the advantage that you have less things to compile.

**Comment by martinKgG** [comment]
Hi,

this is my first time with git and my first android project...

I didn't make it with building the hole app with fdroid.

So I take godot engine, make a locale git clone an change Cxenoj.csv, Kontroloj/Lingvo.gd and Lingvo.tscn.

Than I import the csv file in godot engine und played the game.

All - expect the guide - seems to work in german.

Now, I don't know how to upload this 3 files + engine.cfg which was changed bei godot engine.

**Comment by HassanHeydariNasab** [comment]
push your commits to your forked repository and make a pull request. if you don't know how git works, firstly learn it! :smiley:

**Comment by martinKgG** [comment]
remote: Permission to HassanHeydariNasab/defendo.git denied to martinKgG.
fatal: unable to access 'https://github.com/HassanHeydariNasab/defendo.git/': The requested URL returned error: 403
Pushing to https://github.com/HassanHeydariNasab/defendo.git

**Comment by HassanHeydariNasab** [comment]
You must fork my repository on github and then clone your own forked repository

**Comment by martinKgG** [comment]
Ok, I see I have a lot to learn. Thanks.
