### ISSUE TITLE
accept donations

### ISSUE THREAD

**Issue by davidak** [HassanHeydariNasab/defendo#50]
@HassanHeydariNasab would you like to receive donations?

You can also forward a part to Godot and put bountied on Bountysource, so others contributing to the game and solving issues get payed (a little).

I suggest allow PayPal (Credit Card, SEPA), Bitcoin, Litecoin and Dogecoin (lower value, so lower transaction fees than BTC).

**Comment by HassanHeydariNasab** [comment]
I have neither PayPal account nor other international credit cards. I'm in Iran! :smile: 
Do anyone else use Litecoin or Dogecoin? :thinking:
I think that Bitcoin is enough.

**Comment by davidak** [comment]
@HassanHeydariNasab Bitcoin has currently very high transaction fees. Sometimes $8 or more! So it's not usable for small amounts. LTC and DOGE are still nearly 0. You can exchange them (i recommend Poloniex). Maybe there is also a service where you can get your local currency for crypto?

https://bitinfocharts.com/comparison/bitcoin-transactionfees.html#6m
