### ISSUE TITLE
only get needed permissions

### ISSUE THREAD

**Issue by davidak** [HassanHeydariNasab/defendo#51]
currently there is a long list of permissions visible on F-Droid. I think they are not all needed.

- godot.ACCESS_CHECKIN_PROPERTIES
- godot.ACCESS_COARSE_LOCATION
- godot.ACCESS_FINE_LOCATION
- godot.ACCESS_LOCATION_EXTRA_COMMANDS
- godot.ACCESS_MOCK_LOCATION
- godot.ACCESS_NETWORK_STATE
- godot.ACCESS_SURFACE_FLINGER
- godot.ACCESS_WIFI_STATE
- godot.ACCOUNT_MANAGER
- godot.ADD_VOICEMAIL
- godot.AUTHENTICATE_ACCOUNTS
- godot.BATTERY_STATS
- godot.BIND_ACCESSIBILITY_SERVICE
- godot.BIND_APPWIDGET
- godot.BIND_DEVICE_ADMIN
- godot.BIND_INPUT_METHOD
- godot.BIND_NFC_SERVICE
- godot.BIND_NOTIFICATION_LISTENER_SERVICE
- godot.BIND_PRINT_SERVICE
- godot.BIND_REMOTEVIEWS
- godot.BIND_TEXT_SERVICE
- godot.BIND_VPN_SERVICE
- godot.BIND_WALLPAPER
- godot.BLUETOOTH
- godot.BLUETOOTH_ADMIN
- godot.BLUETOOTH_PRIVILEGED
- godot.BRICK
- godot.BROADCAST_PACKAGE_REMOVED
- godot.BROADCAST_SMS
- godot.BROADCAST_STICKY
- godot.BROADCAST_WAP_PUSH
- godot.CALL_PHONE
- godot.CALL_PRIVILEGED
- godot.CAMERA
- godot.CAPTURE_AUDIO_OUTPUT
- godot.CAPTURE_SECURE_VIDEO_OUTPUT
- godot.CAPTURE_VIDEO_OUTPUT
- godot.CHANGE_COMPONENT_ENABLED_STATE
- godot.CHANGE_CONFIGURATION
- godot.CHANGE_NETWORK_STATE
- godot.CHANGE_WIFI_MULTICAST_STATE
- godot.CHANGE_WIFI_STATE
- godot.CLEAR_APP_CACHE
- godot.CLEAR_APP_USER_DATA
- godot.CONTROL_LOCATION_UPDATES
- godot.DELETE_CACHE_FILES
- godot.DELETE_PACKAGES
- godot.DEVICE_POWER
- godot.DIAGNOSTIC
- godot.DISABLE_KEYGUARD
- godot.DUMP
- godot.EXPAND_STATUS_BAR
- godot.FACTORY_TEST
- godot.FLASHLIGHT
- godot.FORCE_BACK
- godot.GET_ACCOUNTS
- godot.GET_PACKAGE_SIZE
- godot.GET_TASKS
- godot.GET_TOP_ACTIVITY_INFO
- godot.GLOBAL_SEARCH
- godot.HARDWARE_TEST
- godot.INJECT_EVENTS
- godot.INSTALL_LOCATION_PROVIDER
- godot.INSTALL_PACKAGES
- godot.INSTALL_SHORTCUT
- godot.INTERNAL_SYSTEM_WINDOW
- godot.INTERNET
- godot.KILL_BACKGROUND_PROCESSES
- godot.LOCATION_HARDWARE
- godot.MANAGE_ACCOUNTS
- godot.MANAGE_APP_TOKENS
- godot.MANAGE_DOCUMENTS
- godot.MASTER_CLEAR
- godot.MEDIA_CONTENT_CONTROL
- godot.MODIFY_AUDIO_SETTINGS
- godot.MODIFY_PHONE_STATE
- godot.MOUNT_FORMAT_FILESYSTEMS
- godot.MOUNT_UNMOUNT_FILESYSTEMS
- godot.NFC
- godot.PERSISTENT_ACTIVITY
- godot.PROCESS_OUTGOING_CALLS
- godot.READ_CALENDAR
- godot.READ_CALL_LOG
- godot.READ_CONTACTS
- godot.READ_EXTERNAL_STORAGE
- godot.READ_FRAME_BUFFER
- godot.READ_HISTORY_BOOKMARKS
- godot.READ_INPUT_STATE
- godot.READ_LOGS
- godot.READ_PHONE_STATE
- godot.READ_PROFILE
- godot.READ_SMS
- godot.READ_SOCIAL_STREAM
- godot.READ_SYNC_SETTINGS
- godot.READ_SYNC_STATS
- godot.READ_USER_DICTIONARY
- godot.REBOOT
- godot.RECEIVE_BOOT_COMPLETED
- godot.RECEIVE_MMS
- godot.RECEIVE_SMS
- godot.RECEIVE_WAP_PUSH
- godot.RECORD_AUDIO
- godot.REORDER_TASKS
- godot.RESTART_PACKAGES
- godot.SEND_RESPOND_VIA_MESSAGE
- godot.SEND_SMS
- godot.SET_ACTIVITY_WATCHER
- godot.SET_ALARM
- godot.SET_ALWAYS_FINISH
- godot.SET_ANIMATION_SCALE
- godot.SET_DEBUG_APP
- godot.SET_ORIENTATION
- godot.SET_POINTER_SPEED
- godot.SET_PREFERRED_APPLICATIONS
- godot.SET_PROCESS_LIMIT
- godot.SET_TIME
- godot.SET_TIME_ZONE
- godot.SET_WALLPAPER
- godot.SET_WALLPAPER_HINTS
- godot.SIGNAL_PERSISTENT_PROCESSES
- godot.STATUS_BAR
- godot.SUBSCRIBED_FEEDS_READ
- godot.SUBSCRIBED_FEEDS_WRITE
- godot.SYSTEM_ALERT_WINDOW
- godot.TRANSMIT_IR
- godot.UNINSTALL_SHORTCUT
- godot.UPDATE_DEVICE_STATS
- godot.USE_CREDENTIALS
- godot.USE_SIP
- godot.VIBRATE
- godot.WAKE_LOCK
- godot.WRITE_APN_SETTINGS
- godot.WRITE_CALENDAR
- godot.WRITE_CALL_LOG
- godot.WRITE_CONTACTS
- godot.WRITE_EXTERNAL_STORAGE
- godot.WRITE_GSERVICES
- godot.WRITE_HISTORY_BOOKMARKS
- godot.WRITE_PROFILE
- godot.WRITE_SECURE_SETTINGS
- godot.WRITE_SETTINGS
- godot.WRITE_SMS
- godot.WRITE_SOCIAL_STREAM
- godot.WRITE_SYNC_SETTINGS
- godot.WRITE_USER_DICTIONARY
- godot.custom.0
- godot.custom.1
- godot.custom.2
- godot.custom.3
- godot.custom.4
- godot.custom.5
- godot.custom.6
- godot.custom.7
- godot.custom.8
- godot.custom.9
- godot.custom.10
- godot.custom.11
- godot.custom.12
- godot.custom.13
- godot.custom.14
- godot.custom.15
- godot.custom.16
- godot.custom.17
- godot.custom.18
- godot.custom.19

**Comment by HassanHeydariNasab** [comment]
https://github.com/godotengine/godot/issues/1813
