### ISSUE TITLE
Donate Button in About Screen does Nothing

### ISSUE THREAD

**Issue by thewizardstudio** [HassanHeydariNasab/defendo#59]
#### Expected Behavior
The Donate button in the About screen takes the User to a location where they can donate to the developer.

#### Actual Behavior
Nothing happens when the User taps the Donate button on the About screen.

#### How to Reproduce
1. Launch Defendo 2.5.0 on Android 8.1.0
2. Tap About
3. Tap Donate

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 2.5.0
---

#### Recording of the Bug
![DonateButtonBroken.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517104471/adudygf8g5cltgwk7lix.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/donate-button-in-about-screen-does-nothing">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by HassanHeydariNasab** [comment]
You should install a Bitcoin wallet in order to open this Bitcoin address.
Also see https://github.com/HassanHeydariNasab/defendo/commit/b1f154e4f1a031743faef1233c9087c0763c99d6
