### ISSUE TITLE
Money is subtracted instead of summed

### ISSUE THREAD

**Issue by rugk** [HassanHeydariNasab/defendo#7]
In groups of 10 the $$$ is subtracted by 1 when defeating an enemy. So it goes: 19, 18, 17, 16, 15, 14, 13, 12, 11, 20

As you see, it ends correctly. (otherwise we would not get any money, of course)

**Comment by HassanHeydariNasab** [comment]
every shoot by cannon costs 1$ and others except the bombs costs 5$

**Comment by rugk** [comment]
Ah, when I know that, I can understand it at least. But it really looks like a bug… Why do I have to pay for shooting, I already pay for the weapons…

At least you should explain it somewhere.

**Comment by HassanHeydariNasab** [comment]
It is an encourage for upgrading weapons instead of more weapons.
And in the real world it seems more logical.

**Comment by rugk** [comment]
Yeah, but users should know that.

**Comment by HassanHeydariNasab** [comment]
https://github.com/HassanHeydariNasab/defendo/commit/51d2bbe1c6dcabe5e4b0d8f72992e5a637b10c7e
also I informed user in the guide.
