### ISSUE TITLE
Player looses before enemy hits base

### ISSUE THREAD

**Issue by rugk** [HassanHeydariNasab/defendo#8]
I always get the "You lost" message when the space ship or what it is, is still quite far away from my base.

I mean it maybe does some "foreseeing" and when I did nothing I would indeed loose. (I've always interpreted the message as "You will loose", because of that.) 
But **I could** still do something, drop bombs or so, to prevent that.

In any case, even if I could not do anything, users should see, that they loose. Otherwise they say: "Hey, I don't believe you!" when the app says "You loose" (BTW, does it say "You loose" instead of "You lost" :smile:?)

**Comment by HassanHeydariNasab** [comment]
As I mentioned on #7 the shooting consumes money and while you haven't money, you would be lost!
Yes, I forgot the Bombs! (bombs do not consume money)

**Comment by rugk** [comment]
Okay, if you want to keep that, at least show the user that they cannot shoot anymore and let the enemies hit the base.
